name = "Boltzmann"
uuid = "f252d6a7-0c63-4370-b21c-06c34ff2c5e3"
authors = ["Daniel Forero"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
